MODEL_SIZE = 128
OUTPUT_CHANNELS = 3
EPOCHS_NUM = 10

SRC_PATH = 'src'
IMG_PATH = SRC_PATH + r'\img'
MASK_PATH = SRC_PATH + r'\mask'
DATASET_ROOT = SRC_PATH + r'\dataset'
MODEL_PATH = SRC_PATH + r'\model'

WORK_SPACE = 'workspace'
UN_PRODUCED_FILE_PTAH = WORK_SPACE + r'\bef'
PRODUCED_FILE_PATH = WORK_SPACE + r'\aft'

